# Generated by Django 4.1 on 2022-11-03 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='name')),
                ('email', models.CharField(max_length=24, verbose_name='email')),
                ('subject', models.CharField(max_length=512, verbose_name='subject')),
                ('message', models.CharField(max_length=512, verbose_name='message')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 24, 12, 849576, tzinfo=datetime.timezone.utc), verbose_name='date created')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'blog_contacts',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='title')),
                ('subtitle', models.CharField(max_length=24, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 24, 12, 849240, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'blog_posts',
                'ordering': ('date_published',),
            },
        ),
    ]
